import { Zikr } from "../types";

const items: Zikr[] = [
  {
    id: 1,
    ar: {
      prefix: "",
      text: "اللَّهُمَّ ارْحَمْنِي بالقُرْءَانِ وَاجْعَلهُ لِي إِمَاماً وَنُوراً وَهُدًى وَرَحْمَةً *\n\nاللَّهُمَّ ذَكِّرْنِي مِنْهُ مَا نَسِيتُ وَعَلِّمْنِي مِنْهُ مَا جَهِلْتُ وَارْزُقْنِي تِلاَوَتَهُ آنَاءَ اللَّيْلِ وَأَطْرَافَ النَّهَارِ وَاجْعَلْهُ لِي حُجَّةً يَا رَبَّ العَالَمِينَ *\n\nاللَّهُمَّ أَصْلِحْ لِي دِينِي الَّذِي هُوَ عِصْمَةُ أَمْرِي، وَأَصْلِحْ لِي دُنْيَايَ الَّتِي فِيهَا مَعَاشِي، وَأَصْلِحْ لِي آخِرَتِي الَّتِي فِيهَا مَعَادِي، وَاجْعَلِ الحَيَاةَ زِيَادَةً لِي فِي كُلِّ خَيْرٍ وَاجْعَلِ المَوْتَ رَاحَةً لِي مِنْ كُلِّ شَرٍّ *\n\nاللَّهُمَّ اجْعَلْ خَيْرَ عُمْرِي آخِرَهُ وَخَيْرَ عَمَلِي خَوَاتِمَهُ وَخَيْرَ أَيَّامِي يَوْمَ أَلْقَاكَ فِيهِ *\n\nاللَّهُمَّ إِنِّي أَسْأَلُكَ عِيشَةً هَنِيَّةً وَمِيتَةً سَوِيَّةً وَمَرَدًّا غَيْرَ مُخْزٍ وَلاَ فَاضِحٍ *\n\nاللَّهُمَّ إِنِّي أَسْأَلُكَ خَيْرَ المَسْأَلةِ وَخَيْرَ الدُّعَاءِ وَخَيْرَ النَّجَاحِ وَخَيْرَ العِلْمِ وَخَيْرَ العَمَلِ وَخَيْرَ الثَّوَابِ وَخَيْرَ الحَيَاةِ وَخيْرَ المَمَاتِ وَثَبِّتْنِي وَثَقِّلْ مَوَازِينِي وَحَقِّقْ إِيمَانِي وَارْفَعْ دَرَجَتِي وَتَقَبَّلْ صَلاَتِي وَاغْفِرْ خَطِيئَاتِي وَأَسْأَلُكَ العُلَا مِنَ الجَنَّةِ *\n\nاللَّهُمَّ إِنِّي أَسْأَلُكَ مُوجِبَاتِ رَحْمَتِكَ وَعَزَائِمِ مَغْفِرَتِكَ وَالسَّلاَمَةَ مِنْ كُلِّ إِثْمٍ وَالغَنِيمَةَ مِنْ كُلِّ بِرٍّ وَالفَوْزَ بِالجَنَّةِ وَالنَّجَاةَ مِنَ النَّارِ *\n\nاللَّهُمَّ أَحْسِنْ عَاقِبَتَنَا فِي الأُمُورِ كُلِّهَا، وَأجِرْنَا مِنْ خِزْيِ الدُّنْيَا وَعَذَابِ الآخِرَةِ *\n\nاللَّهُمَّ اقْسِمْ لَنَا مِنْ خَشْيَتِكَ مَا تَحُولُ بِهِ بَيْنَنَا وَبَيْنَ مَعْصِيَتِكَ وَمِنْ طَاعَتِكَ مَا تُبَلِّغُنَا بِهَا جَنَّتَكَ وَمِنَ اليَقِينِ مَا تُهَوِّنُ بِهِ عَلَيْنَا مَصَائِبَ الدُّنْيَا وَمَتِّعْنَا بِأَسْمَاعِنَا وَأَبْصَارِنَا وَقُوَّتِنَا مَا أَحْيَيْتَنَا وَاجْعَلْهُ الوَارِثَ مِنَّا وَاجْعَلْ ثَأْرَنَا عَلَى مَنْ ظَلَمَنَا وَانْصُرْنَا عَلَى مَنْ عَادَانَا وَلاَ تجْعَلْ مُصِيبَتَنَا فِي دِينِنَا وَلاَ تَجْعَلِ الدُّنْيَا أَكْبَرَ هَمِّنَا وَلَا مَبْلَغَ عِلْمِنَا وَلاَ تُسَلِّطْ عَلَيْنَا مَنْ لَا يَرْحَمُنَا *\n\nاللَّهُمَّ لَا تَدَعْ لَنَا ذَنْبًا إِلَّا غَفَرْتَهُ وَلَا هَمًّا إِلَّا فَرَّجْتَهُ وَلَا دَيْنًا إِلَّا قَضَيْتَهُ وَلَا حَاجَةً مِنْ حَوَائِجِ الدُّنْيَا وَالآخِرَةِ إِلَّا قَضَيْتَهَا يَا أَرْحَمَ الرَّاحِمِينَ *\n\nرَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ وَصَلَّى اللهُ عَلَى سَيِّدِنَا وَنَبِيِّنَا مُحَمَّدٍ وَعَلَى آلِهِ وَأَصْحَابِهِ الأَخْيَارِ وَسَلَّمَ تَسْلِيمًا كَثِيراً.",
      suffix: "",
      virtue: "",
      source: "دعاء مأثور، وبعض فقراته من أدعية نبوية ثابتة",
    },
    en: {
      prefix: "",
      text: "O Allah, have mercy on me through the Quran, and make it for me a guide, a light, guidance and mercy. *\n\nO Allah, remind me of what I have forgotten of it, teach me what I do not know of it, grant me its recitation during the hours of the night and the ends of the day, and make it a proof for me, O Lord of the worlds. *\n\nO Allah, set right for me my religion, which is the safeguard of my affairs; set right for me my worldly life, in which is my livelihood; and set right for me my Hereafter, to which is my return. Make life an increase for me in every good, and make death a relief for me from every evil. *\n\nO Allah, make the best of my life its end, the best of my deeds their final ones, and the best of my days the day I meet You. *\n\nO Allah, I ask You for a pleasant life, a sound death, and a return [to You] that is neither disgraceful nor shameful. *\n\nO Allah, I ask You for the best of requests, the best of supplication, the best of success, the best of knowledge, the best of deeds, the best of reward, the best of life and the best of death. Make me steadfast, make my scales heavy, make my faith true, raise my rank, accept my prayer, forgive my sins, and I ask You for the highest ranks of Paradise. *\n\nO Allah, I ask You for what makes Your mercy certain and Your forgiveness assured, safety from every sin, a share in every righteous deed, success in attaining Paradise and deliverance from the Fire. *\n\nO Allah, make good the outcome of all our affairs, and protect us from the disgrace of this world and the punishment of the Hereafter. *\n\nO Allah, apportion to us such fear of You as will come between us and disobeying You, such obedience to You as will bring us to Your Paradise, and such certainty as will make the calamities of this world easy for us. Let us enjoy our hearing, our sight and our strength as long as You keep us alive, and make them the heir from us. Let our vengeance be upon those who wronged us, grant us victory over those who show us enmity, do not let our calamity be in our religion, do not make this world our greatest concern or the limit of our knowledge, and do not give power over us to those who will not show us mercy. *\n\nO Allah, leave us no sin but that You forgive it, no worry but that You relieve it, no debt but that You settle it, and no need of the needs of this world and the Hereafter but that You fulfill it, O Most Merciful of the merciful. *\n\nOur Lord, give us in this world [that which is] good and in the Hereafter [that which is] good and protect us from the punishment of the Fire. And may Allah send abundant blessings and peace upon our master and prophet Muhammad, and upon his family and his noble companions..",
      suffix: "",
      virtue: "",
      source:
        "A traditional supplication; some of its passages are from authentic Prophetic supplications",
    },
    count: 1,
  },
];

export default items;
