import { AzkarCategory } from "./types";

const categories: AzkarCategory[] = [
  {
    id: "morning_azkar",
    title: { ar: "أذكار الصباح", en: "Morning Adhkar" },
    featured: true,
    goals: [
      { id: 1, count: 1 },
      { id: 2, count: 3 },
      { id: 3, count: 3 },
      { id: 4, count: 3 },
      { id: 5, count: 1 },
      { id: 6, count: 1 },
      { id: 7, count: 3 },
      { id: 8, count: 4 },
      { id: 9, count: 1 },
      { id: 10, count: 7 },
      { id: 11, count: 3 },
      { id: 12, count: 1 },
      { id: 13, count: 1 },
      { id: 14, count: 3 },
      { id: 15, count: 3 },
      { id: 16, count: 3 },
      { id: 17, count: 1 },
      { id: 18, count: 3 },
      { id: 19, count: 1 },
      { id: 20, count: 1 },
      { id: 21, count: 3 },
      { id: 22, count: 10 },
      { id: 23, count: 3 },
      { id: 24, count: 3 },
      { id: 25, count: 3 },
      { id: 26, count: 3 },
      { id: 27, count: 1 },
      { id: 28, count: 1 },
      { id: 29, count: 100 },
      { id: 30, count: 100 },
      { id: 31, count: 100 },
    ],
  },
  {
    id: "evening_azkar",
    title: { ar: "أذكار المساء", en: "Evening Adhkar" },
    featured: true,
    goals: [
      { id: 1, count: 1 },
      { id: 2, count: 1 },
      { id: 3, count: 3 },
      { id: 4, count: 3 },
      { id: 5, count: 3 },
      { id: 6, count: 1 },
      { id: 7, count: 1 },
      { id: 8, count: 3 },
      { id: 9, count: 4 },
      { id: 10, count: 1 },
      { id: 11, count: 7 },
      { id: 12, count: 3 },
      { id: 13, count: 1 },
      { id: 14, count: 1 },
      { id: 15, count: 3 },
      { id: 16, count: 3 },
      { id: 17, count: 3 },
      { id: 18, count: 1 },
      { id: 19, count: 3 },
      { id: 20, count: 1 },
      { id: 21, count: 1 },
      { id: 22, count: 3 },
      { id: 23, count: 10 },
      { id: 24, count: 3 },
      { id: 25, count: 3 },
      { id: 26, count: 3 },
      { id: 27, count: 3 },
      { id: 28, count: 100 },
      { id: 29, count: 1 },
      { id: 30, count: 100 },
    ],
  },
  {
    id: "prayer_later_azkar",
    title: { ar: "أذكار بعد الصلاة", en: "After Prayer" },
    featured: true,
    resetEachPrayer: true,
    goals: [
      { id: 1, count: 1 },
      { id: 2, count: 1 },
      { id: 3, count: 1 },
      { id: 4, count: 33 },
      { id: 5, count: 1 },
      { id: 6, count: 3 },
      { id: 7, count: 1 },
      { id: 8, count: 10 },
      { id: 9, count: 1 },
      { id: 10, count: 7 },
      { id: 11, count: 1 },
    ],
  },
  {
    id: "sleep_azkar",
    title: { ar: "أذكار النوم", en: "Before Sleeping" },
    featured: true,
    goals: [
      { id: 1, count: 3 },
      { id: 2, count: 1 },
      { id: 3, count: 1 },
      { id: 4, count: 1 },
      { id: 5, count: 1 },
      { id: 6, count: 1 },
      { id: 7, count: 1 },
      { id: 8, count: 33 },
      { id: 14, count: 33 },
      { id: 15, count: 34 },
      { id: 9, count: 1 },
      { id: 10, count: 1 },
      { id: 11, count: 1 },
      { id: 12, count: 1 },
      { id: 13, count: 1 },
    ],
  },
  {
    id: "friday_salawat",
    title: { ar: "الصلاة على النبي ﷺ", en: "Salawat on the Prophet ﷺ" },
    featured: true,
    fridayOnly: true,
    goals: [{ id: 1, count: 100 }],
  },
  {
    id: "wake_up_azkar",
    title: { ar: "أذكار الاستيقاظ", en: "Upon Waking Up" },
    featured: false,
    goals: [
      { id: 1, count: 1 },
      { id: 2, count: 1 },
      { id: 3, count: 1 },
    ],
  },
  {
    id: "adhan_azkar",
    title: { ar: "أذكار الأذان", en: "The Adhan" },
    featured: false,
    goals: [
      { id: 1, count: 1 },
      { id: 2, count: 1 },
      { id: 3, count: 1 },
      { id: 4, count: 1 },
      { id: 5, count: 1 },
      { id: 6, count: 1 },
      { id: 7, count: 1 },
      { id: 8, count: 1 },
      { id: 9, count: 1 },
    ],
  },
  {
    id: "wudu_azkar",
    title: { ar: "أذكار الوضوء", en: "Ablution" },
    featured: false,
    goals: [
      { id: 1, count: 1 },
      { id: 2, count: 1 },
    ],
  },
  {
    id: "mosque_azkar",
    title: { ar: "أذكار المسجد", en: "The Mosque" },
    featured: false,
    goals: [
      { id: 1, count: 1 },
      { id: 2, count: 1 },
      { id: 3, count: 1 },
    ],
  },
  {
    id: "home_azkar",
    title: { ar: "أذكار المنزل", en: "The Home" },
    featured: false,
    goals: [
      { id: 1, count: 1 },
      { id: 2, count: 1 },
    ],
  },
  {
    id: "khala_azkar",
    title: { ar: "أذكار الخلاء", en: "The Restroom" },
    featured: false,
    goals: [
      { id: 1, count: 1 },
      { id: 2, count: 1 },
    ],
  },
  {
    id: "food_azkar",
    title: { ar: "أذكار الطعام", en: "Food & Drink" },
    featured: false,
    goals: [
      { id: 1, count: 1 },
      { id: 2, count: 1 },
      { id: 3, count: 1 },
      { id: 4, count: 1 },
      { id: 5, count: 1 },
    ],
  },
  {
    id: "hajj_and_umrah_azkar",
    title: { ar: "أذكار الحج والعمرة", en: "Hajj & Umrah" },
    featured: false,
    goals: [
      { id: 1, count: 1 },
      { id: 2, count: 1 },
    ],
  },
  {
    id: "clothing_azkar",
    title: { ar: "أدعية اللباس", en: "Clothing Duas" },
    featured: false,
    goals: [
      { id: 1, count: 1 },
      { id: 2, count: 1 },
    ],
  },
  {
    id: "distress_azkar",
    title: { ar: "أدعية الكرب والهم", en: "Duas for Distress & Worry" },
    featured: false,
    goals: [
      { id: 3, count: 1 },
      { id: 4, count: 1 },
      { id: 5, count: 1 },
      { id: 16, count: 1 },
      { id: 29, count: 1 },
      { id: 33, count: 1 },
    ],
  },
  {
    id: "nature_azkar",
    title: { ar: "أدعية الطبيعة", en: "Nature & Weather Duas" },
    featured: false,
    goals: [
      { id: 6, count: 1 },
      { id: 7, count: 1 },
      { id: 9, count: 1 },
      { id: 28, count: 1 },
    ],
  },
  {
    id: "travel_azkar",
    title: { ar: "أدعية السفر", en: "Travel Duas" },
    featured: false,
    goals: [
      { id: 10, count: 1 },
      { id: 11, count: 1 },
      { id: 12, count: 1 },
      { id: 13, count: 1 },
      { id: 14, count: 1 },
    ],
  },
  {
    id: "prayer_duas",
    title: { ar: "أدعية الصلاة", en: "Duas in Prayer" },
    featured: false,
    goals: [
      { id: 15, count: 1 },
      { id: 34, count: 1 },
      { id: 35, count: 1 },
      { id: 36, count: 1 },
    ],
  },
  {
    id: "repentance_azkar",
    title: { ar: "أدعية الاستغفار والتوبة", en: "Forgiveness & Repentance" },
    featured: false,
    goals: [
      { id: 17, count: 1 },
      { id: 38, count: 1 },
      { id: 40, count: 1 },
      { id: 42, count: 1 },
    ],
  },
  {
    id: "sickness_azkar",
    title: { ar: "أدعية المرض والعافية", en: "Sickness & Wellbeing" },
    featured: false,
    goals: [
      { id: 20, count: 1 },
      { id: 30, count: 1 },
      { id: 31, count: 1 },
      { id: 41, count: 3 },
      { id: 42, count: 7 },
    ],
  },
  {
    id: "marriage_azkar",
    title: { ar: "أدعية الزواج", en: "Marriage Duas" },
    featured: false,
    goals: [
      { id: 22, count: 1 },
      { id: 23, count: 1 },
      { id: 24, count: 1 },
    ],
  },
  {
    id: "daily_life_azkar",
    title: { ar: "أدعية المواقف اليومية", en: "Everyday Situations" },
    featured: false,
    goals: [
      { id: 8, count: 1 },
      { id: 18, count: 100 },
      { id: 19, count: 1 },
      { id: 21, count: 1 },
      { id: 25, count: 1 },
      { id: 26, count: 1 },
      { id: 27, count: 1 },
      { id: 32, count: 1 },
      { id: 37, count: 1 },
      { id: 39, count: 1 },
    ],
  },
  {
    id: "prophetic_duas",
    title: { ar: "أدعية نبوية", en: "Prophetic Duas" },
    featured: false,
    goals: [
      { id: 1, count: 1 },
      { id: 2, count: 1 },
      { id: 3, count: 1 },
      { id: 4, count: 1 },
      { id: 5, count: 1 },
      { id: 6, count: 1 },
      { id: 7, count: 1 },
      { id: 8, count: 1 },
      { id: 9, count: 1 },
      { id: 10, count: 1 },
      { id: 11, count: 1 },
      { id: 12, count: 1 },
      { id: 13, count: 1 },
      { id: 14, count: 1 },
      { id: 15, count: 1 },
      { id: 16, count: 1 },
      { id: 17, count: 1 },
      { id: 18, count: 1 },
      { id: 19, count: 1 },
      { id: 20, count: 1 },
      { id: 21, count: 1 },
      { id: 22, count: 1 },
      { id: 23, count: 1 },
      { id: 24, count: 1 },
      { id: 25, count: 1 },
      { id: 26, count: 1 },
      { id: 27, count: 1 },
      { id: 28, count: 1 },
      { id: 29, count: 1 },
    ],
  },
  {
    id: "quran_duas",
    title: { ar: "أدعية قرآنية", en: "Quranic Duas" },
    featured: false,
    goals: [
      { id: 1, count: 1 },
      { id: 2, count: 1 },
      { id: 3, count: 1 },
      { id: 4, count: 1 },
      { id: 5, count: 1 },
      { id: 6, count: 1 },
      { id: 7, count: 1 },
      { id: 8, count: 1 },
      { id: 9, count: 1 },
      { id: 10, count: 1 },
      { id: 11, count: 1 },
      { id: 12, count: 1 },
      { id: 13, count: 1 },
      { id: 14, count: 1 },
      { id: 15, count: 1 },
      { id: 16, count: 1 },
      { id: 17, count: 1 },
      { id: 18, count: 1 },
      { id: 19, count: 1 },
      { id: 20, count: 1 },
      { id: 21, count: 1 },
      { id: 22, count: 1 },
      { id: 23, count: 1 },
      { id: 24, count: 1 },
      { id: 25, count: 1 },
      { id: 26, count: 1 },
    ],
  },
  {
    id: "prophets_duas",
    title: { ar: "أدعية الأنبياء", en: "Duas of the Prophets" },
    featured: false,
    goals: [
      { id: 1, count: 1 },
      { id: 2, count: 1 },
      { id: 3, count: 1 },
      { id: 4, count: 1 },
      { id: 5, count: 1 },
      { id: 6, count: 1 },
      { id: 7, count: 1 },
      { id: 8, count: 1 },
      { id: 9, count: 1 },
      { id: 10, count: 1 },
      { id: 11, count: 1 },
      { id: 12, count: 1 },
      { id: 13, count: 1 },
    ],
  },
  {
    id: "quran_completion_duas",
    title: { ar: "دعاء ختم القرآن", en: "Dua for Completing the Quran" },
    featured: false,
    goals: [{ id: 1, count: 1 }],
  },
];

export default categories;
