export const MOVED_FROM = "miscellaneous_azkar";

export const MOVED_TO: Record<number, string> = {
  1: "clothing_azkar",
  2: "clothing_azkar",
  3: "distress_azkar",
  4: "distress_azkar",
  5: "distress_azkar",
  16: "distress_azkar",
  29: "distress_azkar",
  33: "distress_azkar",
  6: "nature_azkar",
  7: "nature_azkar",
  9: "nature_azkar",
  28: "nature_azkar",
  10: "travel_azkar",
  11: "travel_azkar",
  12: "travel_azkar",
  13: "travel_azkar",
  14: "travel_azkar",
  15: "prayer_duas",
  34: "prayer_duas",
  35: "prayer_duas",
  36: "prayer_duas",
  17: "repentance_azkar",
  38: "repentance_azkar",
  40: "repentance_azkar",
  42: "repentance_azkar",
  20: "sickness_azkar",
  30: "sickness_azkar",
  31: "sickness_azkar",
  41: "sickness_azkar",
  22: "marriage_azkar",
  23: "marriage_azkar",
  24: "marriage_azkar",
  8: "daily_life_azkar",
  18: "daily_life_azkar",
  19: "daily_life_azkar",
  21: "daily_life_azkar",
  25: "daily_life_azkar",
  26: "daily_life_azkar",
  27: "daily_life_azkar",
  32: "daily_life_azkar",
  37: "daily_life_azkar",
  39: "daily_life_azkar",
};
